Refactored and simplified fanout with improvements from incoming chunk iterator PRs.
kakkoyun/prometheus pull request #3
Opened 2020-05-28 21:48 UTC by bwplotka

## Changes:

* Secondary logic is hidden, instead of weird failed series set logic we had.
* Fanout is well commented
* Fanout closing record all errors
* MergeQuerier improved API (clearer)
* deferredGenericMergeSeriesSet is not needed as we return no samples anyway for failed series sets (next = false).

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

2020-05-28 21:49 UTC, bwplotka commented
Unfortunately, we need to merge this if we want CI ): 

There is one todo but it's super late so let's do it tomorrow. PTAL @kakkoyun

2020-05-29 09:22 UTC, kakkoyun requested changes
Looks great much easier on the eyes :)
I had a quick look at it and I want to mediate on it a bit more.

Besides the nits, my major concern is; this removes the ability to exec async request against queriers.
Both `mergeSeriesSet` and `secondarySeriesSet` constructed with `newGenericMergeSeriesSet()` and it advances all the set at least once. So fanned out `.Select` calls are must be completed before leaving the overarching `.Select` call. Thus I had put the deferred set wrapper in place.

What do you think?

2020-05-29 09:22 UTC, kakkoyun commented on storage/fanout_test.go
> +}
nit: missing line feed.

2020-05-29 09:22 UTC, kakkoyun commented on storage/secondary.go
> +}
nit: missing line feed.

2020-05-29 16:17 UTC, bwplotka commented
Can we merge this to run CI on it? I will address comments on your PR then (:  Plus double check `up/up` case.

2020-05-29 16:19 UTC, kakkoyun approved these changes
Agreed to address, deferred execution on upstream PR.

2020-05-29 16:20 UTC, merged